import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAntecedentes1747440005000 implements MigrationInterface {
  name = 'CreateAntecedentes1747440005000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "antecedentes_heredofamiliares" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "patient_id" uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
        "diabetes" boolean NOT NULL DEFAULT false,
        "diabetes_familiar" varchar(100),
        "diabetes_notas" text,
        "hipertension" boolean NOT NULL DEFAULT false,
        "hipertension_familiar" varchar(100),
        "hipertension_notas" text,
        "cardiopatias" boolean NOT NULL DEFAULT false,
        "cardiopatias_familiar" varchar(100),
        "cardiopatias_notas" text,
        "cancer" boolean NOT NULL DEFAULT false,
        "cancer_tipo" varchar(255),
        "cancer_familiar" varchar(100),
        "cancer_notas" text,
        "enfermedades_respiratorias" boolean NOT NULL DEFAULT false,
        "enfermedades_respiratorias_tipo" varchar(255),
        "enfermedades_respiratorias_familiar" varchar(100),
        "enfermedades_respiratorias_notas" text,
        "enfermedades_renales" boolean NOT NULL DEFAULT false,
        "enfermedades_renales_familiar" varchar(100),
        "enfermedades_renales_notas" text,
        "enfermedades_neurologicas" boolean NOT NULL DEFAULT false,
        "enfermedades_neurologicas_tipo" varchar(255),
        "enfermedades_neurologicas_familiar" varchar(100),
        "enfermedades_neurologicas_notas" text,
        "enfermedades_mentales" boolean NOT NULL DEFAULT false,
        "enfermedades_mentales_tipo" varchar(255),
        "enfermedades_mentales_familiar" varchar(100),
        "enfermedades_mentales_notas" text,
        "otros" jsonb,
        "registrado_por" uuid REFERENCES users(id),
        "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(),
        "ultima_actualizacion" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_heredofamiliares_patient" ON "antecedentes_heredofamiliares" ("patient_id")`);

    await queryRunner.query(`
      CREATE TABLE "antecedentes_personales_patologicos" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "patient_id" uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
        "diabetes_mellitus" boolean NOT NULL DEFAULT false,
        "diabetes_tipo" varchar,
        "diabetes_anio_diagnostico" integer,
        "diabetes_tratamiento" text,
        "diabetes_controlada" boolean,
        "hipertension_arterial" boolean NOT NULL DEFAULT false,
        "hipertension_anio_diagnostico" integer,
        "hipertension_tratamiento" text,
        "hipertension_controlada" boolean,
        "cardiopatias" boolean NOT NULL DEFAULT false,
        "cardiopatias_tipo" varchar(255),
        "cardiopatias_anio_diagnostico" integer,
        "cardiopatias_tratamiento" text,
        "enfermedades_respiratorias" boolean NOT NULL DEFAULT false,
        "enfermedades_respiratorias_tipo" varchar(255),
        "enfermedades_respiratorias_anio_diagnostico" integer,
        "enfermedades_respiratorias_tratamiento" text,
        "enfermedades_renales" boolean NOT NULL DEFAULT false,
        "enfermedades_renales_tipo" varchar(255),
        "enfermedades_renales_anio_diagnostico" integer,
        "enfermedades_renales_tratamiento" text,
        "cancer" boolean NOT NULL DEFAULT false,
        "cancer_tipo" varchar(255),
        "cancer_anio_diagnostico" integer,
        "cancer_tratamiento" text,
        "cancer_remision" boolean,
        "tuberculosis" boolean NOT NULL DEFAULT false,
        "tuberculosis_anio" integer,
        "tuberculosis_tratamiento_completo" boolean,
        "hepatitis" boolean NOT NULL DEFAULT false,
        "hepatitis_tipo" varchar(10),
        "hepatitis_anio" integer,
        "vih_sida" boolean NOT NULL DEFAULT false,
        "vih_anio_diagnostico" integer,
        "vih_tratamiento_antirretroviral" boolean,
        "covid19" boolean NOT NULL DEFAULT false,
        "covid19_fecha" date,
        "covid19_severidad" varchar(50),
        "covid19_secuelas" text,
        "epilepsia" boolean NOT NULL DEFAULT false,
        "epilepsia_controlada" boolean,
        "epilepsia_tratamiento" text,
        "accidente_cerebrovascular" boolean NOT NULL DEFAULT false,
        "accidente_cerebrovascular_fecha" date,
        "accidente_cerebrovascular_tipo" varchar(50),
        "accidente_cerebrovascular_secuelas" text,
        "depresion" boolean NOT NULL DEFAULT false,
        "depresion_tratamiento" text,
        "ansiedad" boolean NOT NULL DEFAULT false,
        "ansiedad_tratamiento" text,
        "otros_psiquiatricos" jsonb,
        "cirugias" jsonb,
        "hospitalizaciones" jsonb,
        "traumatismos" jsonb,
        "alergias_medicamentos" jsonb,
        "alergias_alimentos" jsonb,
        "alergias_otras" jsonb,
        "transfusiones" boolean NOT NULL DEFAULT false,
        "transfusiones_detalle" jsonb,
        "otros" jsonb,
        "registrado_por" uuid REFERENCES users(id),
        "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(),
        "ultima_actualizacion" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_patologicos_patient" ON "antecedentes_personales_patologicos" ("patient_id")`);

    await queryRunner.query(`
      CREATE TABLE "antecedentes_personales_no_patologicos" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "patient_id" uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
        "tabaquismo" boolean NOT NULL DEFAULT false,
        "tabaquismo_tipo" varchar(50),
        "tabaquismo_cigarrillos_dia" integer,
        "tabaquismo_anios_fumando" integer,
        "tabaquismo_anios_sin_fumar" integer,
        "alcoholismo" boolean NOT NULL DEFAULT false,
        "alcoholismo_frecuencia" varchar(50),
        "alcoholismo_cantidad" varchar(100),
        "alcoholismo_tipo" varchar(100),
        "drogas" boolean NOT NULL DEFAULT false,
        "drogas_tipo" varchar(255),
        "drogas_frecuencia" varchar(50),
        "drogas_anios_consumo" integer,
        "cafe" boolean NOT NULL DEFAULT false,
        "cafe_tazas_dia" integer,
        "actividad_fisica" boolean NOT NULL DEFAULT false,
        "actividad_fisica_tipo" varchar(255),
        "actividad_fisica_frecuencia" varchar(50),
        "actividad_fisica_duracion_minutos" integer,
        "actividad_fisica_intensidad" varchar(50),
        "alimentacion_tipo" varchar(50),
        "alimentacion_comidas_dia" integer NOT NULL DEFAULT 3,
        "alimentacion_hidratacion_litros" decimal(3,1),
        "alimentacion_notas" text,
        "horas_sueno_promedio" decimal(3,1),
        "calidad_sueno" varchar(50),
        "trastornos_sueno" boolean NOT NULL DEFAULT false,
        "trastornos_sueno_tipo" varchar(255),
        "tipo_vivienda" varchar(50),
        "servicios_basicos" jsonb,
        "hacinamiento" boolean NOT NULL DEFAULT false,
        "numero_personas_hogar" integer,
        "animales_domesticos" boolean NOT NULL DEFAULT false,
        "animales_tipo" varchar(255),
        "exposicion_quimicos" boolean NOT NULL DEFAULT false,
        "exposicion_quimicos_tipo" text,
        "exposicion_radiacion" boolean NOT NULL DEFAULT false,
        "exposicion_radiacion_tipo" text,
        "exposicion_ruido" boolean NOT NULL DEFAULT false,
        "trabajo_forzado" boolean NOT NULL DEFAULT false,
        "trabajo_turnos_rotativos" boolean NOT NULL DEFAULT false,
        "viajes_recientes" jsonb,
        "esquema_vacunacion_completo" boolean,
        "vacunas" jsonb,
        "otros_habitos" text,
        "registrado_por" uuid REFERENCES users(id),
        "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(),
        "ultima_actualizacion" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_no_patologicos_patient" ON "antecedentes_personales_no_patologicos" ("patient_id")`);

    await queryRunner.query(`
      CREATE TABLE "antecedentes_gineco_obstetricos" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "patient_id" uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
        "menarca_edad" integer,
        "fecha_ultima_menstruacion" date,
        "ciclo_menstrual_regular" boolean,
        "ciclo_menstrual_duracion_dias" integer NOT NULL DEFAULT 28,
        "ciclo_menstrual_notas" text,
        "menstruacion_duracion_dias" integer NOT NULL DEFAULT 5,
        "menstruacion_cantidad" varchar(50),
        "dismenorrea" boolean NOT NULL DEFAULT false,
        "dismenorrea_intensidad" varchar(50),
        "menopausia" boolean NOT NULL DEFAULT false,
        "menopausia_edad" integer,
        "menopausia_sintomas" text,
        "menopausia_terapia_reemplazo" boolean NOT NULL DEFAULT false,
        "inicio_vida_sexual_edad" integer,
        "parejas_sexuales_numero" integer,
        "metodo_anticonceptivo_actual" varchar(100),
        "metodo_anticonceptivo_tiempo_uso_meses" integer,
        "metodos_anticonceptivos_previos" jsonb,
        "citologia_ultima_fecha" date,
        "citologia_resultado" varchar(50),
        "citologia_notas" text,
        "mamografia_ultima_fecha" date,
        "mamografia_resultado" varchar(50),
        "mamografia_notas" text,
        "infecciones_vaginales" boolean NOT NULL DEFAULT false,
        "infecciones_vaginales_tipo" varchar(255),
        "infecciones_vaginales_frecuencia" varchar(50),
        "enfermedad_pelvica_inflamatoria" boolean NOT NULL DEFAULT false,
        "enfermedad_pelvica_inflamatoria_fecha" date,
        "endometriosis" boolean NOT NULL DEFAULT false,
        "endometriosis_tratamiento" text,
        "miomatosis_uterina" boolean NOT NULL DEFAULT false,
        "miomatosis_uterina_cantidad" integer,
        "miomatosis_uterina_tratamiento" text,
        "quistes_ovaricos" boolean NOT NULL DEFAULT false,
        "quistes_ovaricos_tipo" varchar(100),
        "quistes_ovaricos_tratamiento" text,
        "sindrome_ovario_poliquistico" boolean NOT NULL DEFAULT false,
        "its_historial" jsonb,
        "cirugias_ginecologicas" jsonb,
        "gestas" integer NOT NULL DEFAULT 0,
        "partos" integer NOT NULL DEFAULT 0,
        "cesareas" integer NOT NULL DEFAULT 0,
        "abortos" integer NOT NULL DEFAULT 0,
        "abortos_tipo" jsonb,
        "hijos_vivos" integer NOT NULL DEFAULT 0,
        "hijos_muertos" integer NOT NULL DEFAULT 0,
        "embarazos" jsonb,
        "embarazo_actual" boolean NOT NULL DEFAULT false,
        "embarazo_actual_semanas" integer,
        "embarazo_actual_fecha_probable_parto" date,
        "embarazo_actual_control_prenatal" boolean,
        "embarazo_actual_complicaciones" text,
        "preeclampsia" boolean NOT NULL DEFAULT false,
        "eclampsia" boolean NOT NULL DEFAULT false,
        "diabetes_gestacional" boolean NOT NULL DEFAULT false,
        "hemorragia_postparto" boolean NOT NULL DEFAULT false,
        "ruptura_prematura_membranas" boolean NOT NULL DEFAULT false,
        "placenta_previa" boolean NOT NULL DEFAULT false,
        "lactancia_actual" boolean NOT NULL DEFAULT false,
        "otros" text,
        "registrado_por" uuid REFERENCES users(id),
        "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(),
        "ultima_actualizacion" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_gineco_obstetricos_patient" ON "antecedentes_gineco_obstetricos" ("patient_id")`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "antecedentes_gineco_obstetricos"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "antecedentes_personales_no_patologicos"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "antecedentes_personales_patologicos"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "antecedentes_heredofamiliares"`);
  }
}
